### PR TITLE
Bump markdownlint to current version (0.20.1)

### PR DESCRIPTION
**Pull request by polarweasel**
Is there anything else required to use Markdownlint v0.20.1?

### CODE REVIEW

**Comment by DavidAnson** [comment]
Looks like you need to update `package-lock.json` to pass tests?

**Comment by DavidAnson** [comment]
Please also bump the version of `markdownlint-rule-helpers`.

**Comment by polarweasel** [comment]
Thanks! Will do.

**Comment by polarweasel** [comment]
@DavidAnson All set, I think... And thanks for the markdownlint tooling! I use it every day at PubNub in VS Code and the command line, and it's about to get integrated into some CI toolchains. :)

**Comment by DavidAnson** [comment]
Thanks!

**Pull request merged**
