### PR TITLE
Bump version to 0.28.0

### PR DESCRIPTION
**Pull request by EliSchleifer**
Bump version to 0.28.0.
Setup for release to include -j flag

### CODE REVIEW

**Comment by DavidAnson** [comment]
It's common to update the release version right before doing a release. However, I won't be able to do that for another week or two. (It's also best practice to create a new PR for new work to avoid confusion.)

**Comment by EliSchleifer** [comment]
Yeah not sure why that new PR had all those dead commits. I can put together a new one if it helps you.

Tell me more about "update release version right before doing a release" - curious how that differs from what I sent you as a PR.
________________________________

**Comment by DavidAnson** [comment]
No worries. By "do a release", I meant issuing the "npm publish" command that uploads the TGZ to the package servers. There are ways to automate that, but not configured for this project. So that's always a manual "sitting at keyboard" operation. There's nothing wrong about bumping the version days/weeks ahead of that, but it's not my habit.

**Comment by DavidAnson** [comment]
Rendered moot by 09cd9b0 which I did before remembering this was pending.

**Pull request closed without merging**
