### PR TITLE
Fix `Cannot find module 'rc'` error when use npx

### PR DESCRIPTION
**Pull request by shhdgit**
After the v0.28.0 release, there's an error when using npx.

```
npx markdownlint-cli ...
```

error:
```
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module 'rc'
```

### CODE REVIEW

**Comment by DavidAnson** [comment]
Thanks - I'll release an update in a moment. I want to make sure I know why this didn't break tests. (Presumably some devDependency includes rc?)

**Comment by DavidAnson** [comment]
Yup:

```
markdownlint-cli % npm ls rc
markdownlint-cli@0.28.0
└─┬ ava@3.15.0
  └─┬ update-notifier@5.0.1
    └─┬ latest-version@5.1.0
      └─┬ package-json@6.5.0
        ├─┬ registry-auth-token@4.1.1
        │ └── rc@1.2.8
        └─┬ registry-url@5.1.0
          └── rc@1.2.8 deduped
```

**Comment by DavidAnson** [comment]
Sorry, I should have noticed the mistake in the PR.

**Comment by DavidAnson** [comment]
Thanks again, I've published `0.28.1` just now.

**Comment by DavidAnson** [comment]
@flcdrg, just FYI, I wrote this GitHub action to use `markdownlint-cli2`: https://github.com/DavidAnson/markdownlint-cli2-action. It may be faster. And you may not like the approach I took. ;)

**Comment by flcdrg** [comment]
@DavidAnson thanks.. I reckon I used something similar with AzDO Pipelines ages ago. Will take a look 👍

**Pull request merged**
