### PR TITLE
Updated markdownlint so that configurations could be extended

### PR DESCRIPTION
**Pull request by Smenus**
I added a base-config to the tests to show that the extend functionality was working.

### CODE REVIEW

**Comment by mroderick** [comment]
I too would like to use the latest `markdownlint`

@DavidAnson @igorshubovych any chance of getting this merged and getting a new version published to npm?

**Comment by DavidAnson** [comment]
I haven’t seen activity from Igor in a while. I have permission to this repo, but maybe not to publish to npm. I will look into this soon. Sorry!

**Comment by DavidAnson** [comment]
@igorshubovych looks to have been active on GitHub recently, so I’m hopeful we will hear from him soon. If not, it looks like I may have access to update this package on npm - I will try doing so in a week or so if it’s still relevant.

**Comment by mroderick** [comment]
Thank you 🙂

**Comment by DavidAnson** [comment]
Please try version `0.4.0` just published to npm and let me know if you run into any issues. Thanks for your patience and PR!

**Comment by mroderick** [comment]
@DavidAnson it's a success! I've put it to good use: https://github.com/sinonjs/sinon/pull/1616

Thank you 🚀

**Pull request merged**
