### PR TITLE
Fix bad module resolution (#42)

### PR DESCRIPTION
**Pull request by VeselovAlex**
Replace `require.resolve('packagename')`, which looks for packages relative to markdownlint-cli root, with `require.resolve('packagename', {paths})`, where paths are calculated relative to working directory

### CODE REVIEW

**Comment by VeselovAlex** [comment]
Why does is fail on AppVeyor? Looks like it does not copy package from `test\custom-rules\relative-to-cwd\node_modules`

**Comment by DavidAnson** [comment]
AppVeyor uses Windows, if that is not what you use, maybe there is a path issue there?

Regarding the _ APIs, aren’t those undocumented and unsupported? That worries me, as does the Node 8 requirement. I would love if we could figure out a way to get the right behavior on Node 6 with public APIs.

**Comment by VeselovAlex** [comment]
Node 8 is not required. `require.resolve.paths` and `require.resolve(module, paths)` are added to public API in Node 8, so we can use them to search packages relative to working directory. For Node 6 we can use `Module._resolveFilename(filepath, {paths: paths})` as a fallback.

To replace `Module._nodeModulePaths(process.cwd())` we can create custom function to build node resolution path list, but should we? This method is available even in 0.10.25 and was not modified for at least 2 years, so it seems to be stable enough

**Comment by VeselovAlex** [comment]
Tests fixed, seems to an issue with `execa` on Windows

**Comment by DavidAnson** [comment]
Yay!!

(Did you mean to leave that console.log in the code?)

**Comment by DavidAnson** [comment]
I should be able to accept this PR tonight. I’ll also update the markdownlint dependency and investigate the other open issue. Once done, I’ll publish a new version. Thanks for the help!

**Pull request merged**
