### PR TITLE
Fix #10 - Don't output blank line when no results

### LINKED ISSUE #10: Don't print empty lines on valid Markdown
When running `markdownlint-cli` on an valid `.md` file, it prints an empty line. I think it's a good idea to have it output nothing (if it has nothing to output of course).

Having taken a quick look at the source code I'm not sure  if this is a `markdownlint` or `markdownlint-cli` related issue.

https://github.com/DavidAnson/markdownlint/issues/30

### PR DESCRIPTION
**Pull request by davidosomething**

### CODE REVIEW

**Comment by DavidAnson** [comment]
Thank you! Could I ask you to also please update the test to verify the new behavior?

**Comment by davidosomething** [comment]
updated tests

**Comment by DavidAnson** [comment]
Cool, thanks! If you could please squash your work into a single commit, I’ll look at merging this tonight.

**Comment by davidosomething** [comment]
squashed

**Pull request merged**
