### PR TITLE
Update the help for `--enable` & `--disable`

### PR DESCRIPTION
**Pull request by MFTabriz**
to reflect 33f319cf6ae051d0634536475dcd9b7fcd974b9d

### CODE REVIEW

**Comment by DavidAnson** [comment]
I considered this when I made the related change, but did not do it because I feel like it clutters up the list of options. I felt like that list should be more about what the options are instead of general syntax. For example, the two dashes are not needed when the list is the final parameter. I don't feel very strongly about this, but as it's only come up once so far I figured that calling it out in the README would be sufficient.

**Comment by DavidAnson** [comment]
What about just showing the two dashes in the example like you have but not adding the text talking about them?

**Comment by MFTabriz** [comment]
> What about just showing the two dashes in the example like you have but not adding the text talking about them?

Yes. This can give users a hint on how to use those options properly. I updated the files.

**Comment by DavidAnson** [comment]
Thanks!

**Pull request merged**
